import type { BoardPayload } from "./types";

/**
 * Invented example board, drawn from the style B mockups.
 * Served when NOTION_TOKEN is missing. Every screen labels it as example data.
 */
export function exampleBoard(now = Date.now()): BoardPayload {
  const ago = (hours: number) => new Date(now - hours * 3_600_000).toISOString();
  return {
    source: "example",
    syncedAt: new Date(now).toISOString(),
    ideas: [
      {
        id: "idea-tuition",
        name: "TuitionMatch KL",
        status: "Testing",
        problem: "Finding a vetted SPM tutor nearby, within weeks of a WhatsApp group going quiet.",
        customerSegment: "Parents of Form 4–5 students in Subang & Shah Alam",
        updatedAt: ago(2),
      },
      {
        id: "idea-kek",
        name: "Kek Pre-order Shah Alam",
        status: "Pivot",
        problem: "Raya kek sells out, and families only hear about a baker the week of the feast.",
        customerSegment: "Office managers ordering for 20+ staff, via Muslim-owned stalls",
        updatedAt: ago(26),
      },
      {
        id: "idea-invoice",
        name: "Invoice nudge for freelancers",
        status: "Canvas",
        problem: "Freelancers lose more than RM500 a month to late payments.",
        customerSegment: "Solo designers and developers in KL who invoice over WhatsApp",
        updatedAt: ago(80),
      },
      {
        id: "idea-surau",
        name: "Surau finder for road trips",
        status: "Brainstorm",
        problem: "Drivers miss prayer time on the highway because the next surau is not on the map.",
        customerSegment: "Families driving north for balik kampung",
        updatedAt: ago(120),
      },
      {
        id: "idea-durian",
        name: "Raya durian weekend box",
        status: "Persevere",
        problem: "People want a small durian box for the weekend, not a whole seasonal stall.",
        customerSegment: "Neighbours in Shah Alam who already bought once",
        updatedAt: ago(50),
      },
      {
        id: "idea-uniform",
        name: "School uniform swap",
        status: "Parked",
        problem: "Parents will swap uniforms at a school collection box.",
        customerSegment: "Parents of primary pupils, one PIBG at a time",
        updatedAt: ago(200),
      },
    ],
    canvases: [
      {
        id: "canvas-tuition-v1",
        ideaId: "idea-tuition",
        name: "Lean Canvas v1",
        version: 1,
        date: "2026-09-12",
        boxes: {
          problem: "Parents cannot find a tutor they trust.",
          customerSegments: "Parents in Klang Valley",
          uniqueValueProposition: "A tutor this week.",
          solution: "A WhatsApp intro.",
          channels: "Friends of friends",
          revenueStreams: "Unclear",
          costStructure: "Time",
          keyMetrics: "Intros sent",
          unfairAdvantage: "None yet",
        },
      },
      {
        id: "canvas-tuition-v2",
        ideaId: "idea-tuition",
        name: "Lean Canvas v2",
        version: 2,
        date: "2026-10-02",
        boxes: {
          problem:
            "Hard to find a vetted SPM tutor near home\nTutor quality unknown until after paying\nSchedules clash with school and ko-ku\n\nalternatives: WhatsApp groups, tuition centres, word of mouth",
          solution: "Hand-picked shortlist of 3 tutors in 48 h\nFree trial lesson if it is not a fit\nVerified past-results notes",
          uniqueValueProposition: "A vetted SPM tutor near you in 48 hours, first lesson free if it is not a fit.",
          unfairAdvantage: "None yet. Maybe: a network of retired teachers.",
          customerSegments: "Parents of Form 4–5 students, Klang Valley\n\nEarly adopters: parents already asking for tutors in Subang school groups",
          keyMetrics: "Paid match rate\nTrial to monthly conversion\nRepeat matches per family",
          channels: "School parent WhatsApp groups\nPIBG events\nFacebook parent groups\n\nHigh-level concept: Grab for home tuition",
          costStructure: "Vetting time (~2 h per tutor)\nWhatsApp Business + forms\nSmall ads budget",
          revenueStreams: "RM30 matching fee per family\n10% of the first month (tutor side)",
        },
      },
      {
        id: "canvas-kek-v3",
        ideaId: "idea-kek",
        name: "Lean Canvas v3",
        version: 3,
        date: "2026-10-06",
        boxes: {
          problem: "Families order kek too late\nStalls sell out the week of Raya\nOffice pantries have the same snack every month",
          solution: "Pre-order with a pickup slot\nA weekly office snack box from one stall\nPay a deposit to hold the batch",
          uniqueValueProposition: "Reserve a Muslim-owned snack box for the office, a week ahead, so the stall bakes to order.",
          unfairAdvantage: "None yet. A short list of stalls that already sell out.",
          customerSegments: "Office managers in Shah Alam with 20+ staff\nMuslim-owned home bakers who can batch",
          keyMetrics: "Pre-orders that actually pay\nOffices that reorder next month\nBakers who accept a second batch",
          channels: "Office WhatsApp groups\nA one-page form shared by one manager\nInstagram, only as a smoke test",
          costStructure: "Deposit refunds\nPickup crates\nA Saturday morning at the stall",
          revenueStreams: "RM8 per box, office pays the invoice\nStall keeps the food margin",
        },
      },
      {
        id: "canvas-invoice-v1",
        ideaId: "idea-invoice",
        name: "Lean Canvas v1",
        version: 1,
        date: "2026-10-04",
        boxes: {
          problem: "Invoices sent on WhatsApp get buried.\nChasing feels rude, so it waits a month.\nLate fees are never written down.",
          solution: "A nudge drafted in the freelancer's voice, sent on day 7 and day 14.",
          uniqueValueProposition: "Get paid without writing the awkward message yourself.",
          unfairAdvantage: "None yet.",
          customerSegments: "Solo freelancers in KL invoicing under RM5,000",
          keyMetrics: "Invoices paid within 14 days",
          channels: "Designer Discords, a landing page",
          costStructure: "WhatsApp template time",
          revenueStreams: "RM15 per chased invoice, only if it is paid",
        },
      },
      {
        id: "canvas-durian-v1",
        ideaId: "idea-durian",
        name: "Lean Canvas v1",
        version: 1,
        date: "2026-09-20",
        boxes: {
          problem: "A whole durian is too much for one weekend.",
          solution: "A 4-seed box, prepaid on Thursday, picked up Saturday.",
          uniqueValueProposition: "Weekend durian without camping at the stall.",
          unfairAdvantage: "One uncle who already sells on Jalan Plumbum.",
          customerSegments: "Neighbours who bought last month",
          keyMetrics: "Reorder within 3 weeks",
          channels: "The same street WhatsApp group",
          costStructure: "The uncle's wholesale price",
          revenueStreams: "RM28 per box",
        },
      },
    ],
    assumptions: [
      {
        id: "asm-a6",
        ideaId: "idea-tuition",
        code: "A6",
        statement: "Tutors accept a 10% first-month fee",
        type: "Value",
        risk: "Low",
        status: "Invalidated",
      },
      {
        id: "asm-a2",
        ideaId: "idea-tuition",
        code: "A2",
        statement: "Parents trust a shortlist of 3 more than a WhatsApp group",
        type: "Value",
        risk: "High",
        status: "Testing",
      },
      {
        id: "asm-a5",
        ideaId: "idea-tuition",
        code: "A5",
        statement: "Facebook parent-group ads cost < RM20 per lead",
        type: "Growth",
        risk: "Medium",
        status: "Untested",
      },
      {
        id: "asm-a4",
        ideaId: "idea-tuition",
        code: "A4",
        statement: "Enough qualified SPM tutors in Subang will join",
        type: "Value",
        risk: "Medium",
        status: "Validated",
      },
      {
        id: "asm-a3",
        ideaId: "idea-tuition",
        code: "A3",
        statement: "Paying parents refer other parents at the same school",
        type: "Growth",
        risk: "Medium",
        status: "Untested",
      },
      {
        id: "asm-a1",
        ideaId: "idea-tuition",
        code: "A1",
        statement: "Parents will pay a RM30 matching fee before the first lesson",
        type: "Value",
        risk: "High",
        status: "Testing",
      },
      {
        id: "asm-kek-parents",
        ideaId: "idea-kek",
        code: "A1",
        statement: "Parents will pre-order a family kek box 4 weeks ahead",
        type: "Value",
        risk: "High",
        status: "Invalidated",
      },
      {
        id: "asm-kek-office",
        ideaId: "idea-kek",
        code: "A2",
        statement: "Office managers will pre-order snack boxes for 20+ staff monthly",
        type: "Value",
        risk: "High",
        status: "Untested",
      },
      {
        id: "asm-kek-bakers",
        ideaId: "idea-kek",
        code: "A3",
        statement: "Home bakers will hold a batch for a 15% cut",
        type: "Value",
        risk: "Medium",
        status: "Testing",
      },
      {
        id: "asm-durian",
        ideaId: "idea-durian",
        code: "A1",
        statement: "Buyers reorder a weekend box within 3 weeks",
        type: "Value",
        risk: "Medium",
        status: "Validated",
      },
      {
        id: "asm-uniform",
        ideaId: "idea-uniform",
        code: "A1",
        statement: "Parents will swap uniforms at a school collection box",
        type: "Value",
        risk: "Low",
        status: "Untested",
      },
    ],
    experiments: [
      {
        id: "exp-e1",
        ideaId: "idea-tuition",
        assumptionId: "asm-a2",
        code: "E1",
        name: "Parent interviews",
        method: "Interview 10 parents",
        outcome: "Passed",
        successMetric: "Parents who name tutor-finding a top-3 pain",
        target: ">= 6 of 10",
        result: "8 of 10",
        evidence: "Said",
        lockedAt: "2026-09-01",
      },
      {
        id: "exp-e2",
        ideaId: "idea-tuition",
        assumptionId: "asm-a4",
        code: "E2",
        name: "Tutor sign-up form",
        method: "A one-page form shared in two tutor groups",
        outcome: "Passed",
        successMetric: "Qualified tutors who sign up",
        target: ">= 15 in 2 weeks",
        result: "22 vs 15",
        evidence: "Did",
        lockedAt: "2026-09-08",
      },
      {
        id: "exp-e3",
        ideaId: "idea-tuition",
        assumptionId: "asm-a1",
        code: "E3",
        name: "Concierge + RM30 fee",
        method: "Match 10 families by hand and ask for the fee before the trial",
        outcome: "Running",
        successMetric: "Matched parents who pay the fee",
        target: ">= 40% (of 10)",
        result: "3 of 8 so far",
        lockedAt: "2026-09-20",
      },
      {
        id: "exp-e4",
        ideaId: "idea-tuition",
        assumptionId: "asm-a3",
        code: "E4",
        name: "School referral card",
        method: "Give each paying parent one card for another parent",
        outcome: "Planned",
        successMetric: "Referrals per paying parent",
        target: ">= 0.5 referrals",
        lockedAt: "2026-10-01",
      },
      {
        id: "exp-kek-poll",
        ideaId: "idea-kek",
        assumptionId: "asm-kek-parents",
        code: "E1",
        name: "Instagram poll",
        method: "Poll parents: would you pre-order kek 4 weeks ahead?",
        outcome: "Passed",
        successMetric: "Yes votes",
        target: ">= 15 of 20",
        result: "19 of 20",
        evidence: "Said",
        lockedAt: "2026-09-15",
      },
      {
        id: "exp-kek-form",
        ideaId: "idea-kek",
        assumptionId: "asm-kek-parents",
        code: "E2",
        name: "Pre-order form",
        method: "Take a real deposit for a family box",
        outcome: "Failed",
        successMetric: "Paid pre-orders",
        target: ">= 30 of 120",
        result: "6 of 120 (5%)",
        evidence: "Did",
        lockedAt: "2026-09-18",
      },
      {
        id: "exp-kek-office",
        ideaId: "idea-kek",
        assumptionId: "asm-kek-office",
        code: "E3",
        name: "Office snack box trial",
        method: "Ask 8 office managers to pre-order a 20-box week",
        outcome: "Planned",
        successMetric: "Managers who pay a deposit",
        target: ">= 3 of 8",
        lockedAt: "2026-10-06",
      },
      {
        id: "exp-durian",
        ideaId: "idea-durian",
        assumptionId: "asm-durian",
        code: "E1",
        name: "Second-weekend reorder",
        method: "Text last month's buyers a Thursday pre-order",
        outcome: "Passed",
        successMetric: "Buyers who reorder within 3 weeks",
        target: ">= 8 of 20",
        result: "11 of 20",
        evidence: "Did",
        lockedAt: "2026-09-01",
      },
    ],
    learnings: [
      {
        id: "learn-tuition-trust",
        ideaId: "idea-tuition",
        experimentId: "exp-e1",
        insight: "Parents trust a shortlist, and 3 named tutors beat a long list.",
        date: "2026-09-30",
        decision: "Persevere",
        observed: "8 of 10 preferred 3 named tutors over a WhatsApp pile.",
        learned: "A teacher's name they can check builds trust.",
        therefore: "Persevere",
      },
      {
        id: "learn-tuition-supply",
        ideaId: "idea-tuition",
        experimentId: "exp-e2",
        insight: "Tutor supply is not the bottleneck in Subang.",
        date: "2026-09-28",
        observed: "22 qualified tutors signed up. The target was 15.",
        learned: "Supply is there. The open question is whether parents pay before the lesson.",
        therefore: "Keep the concierge running",
      },
      {
        id: "learn-kek-pivot",
        ideaId: "idea-kek",
        experimentId: "exp-kek-form",
        insight: "Half of the 6 paid orders were office staff buying in bulk, not families.",
        date: "2026-10-06",
        decision: "Pivot",
        pivotType: "Customer segment",
        observed: "6 of 120 parents paid. 3 of those 6 were buying for an office.",
        learned: "The family pre-order is too early. The office pantry is already a buyer.",
        therefore: "Pivot",
      },
      {
        id: "learn-durian",
        ideaId: "idea-durian",
        experimentId: "exp-durian",
        insight: "Neighbours came back the next weekend when the box stayed small.",
        date: "2026-09-22",
        decision: "Persevere",
        observed: "11 of 20 reordered and paid before Saturday.",
        learned: "The 4-seed box is the product. A bigger box can wait.",
        therefore: "Persevere",
      },
    ],
  };
}
